import { jsPDF } from 'jspdf';

export const generateDoctorReport = (user, medicines, history, riskLevel, lifetimeScore) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(239, 35, 60); // Primary Red
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text('Unnecessary Antibiotic Risk Report', 20, 20);

    doc.setFontSize(12);
    doc.text(`Patient: ${user?.name || 'Guest'}`, 20, 30);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 140, 30);

    let yPos = 50;

    // Summary Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text('Summary Overview', 20, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.text(`Current Risk Level: ${riskLevel}`, 20, yPos);
    doc.text(`Lifetime Compatibility Score: ${lifetimeScore}%`, 20, yPos + 7);
    yPos += 20;

    // Current Medications
    doc.setFontSize(16);
    doc.text('Current Medications (Active)', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    if (medicines.length > 0) {
        medicines.forEach(med => {
            doc.text(`- ${med.name} (${med.dosage}, ${med.frequency}) - ${med.duration} days`, 25, yPos);
            yPos += 7;
        });
    } else {
        doc.text('No active medications tracked.', 25, yPos);
        yPos += 7;
    }
    yPos += 10;

    // History (Last 10 items)
    doc.setFontSize(16);
    doc.text('Recent History', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    if (history.length > 0) {
        history.slice(0, 10).forEach(med => {
            doc.text(`- [Completed] ${med.name} (${med.dosage})`, 25, yPos);
            yPos += 7;
        });
    } else {
        doc.text('No medication history available.', 25, yPos);
    }

    // Disclaimer
    yPos = 270;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('This report is generated by Medication Ninja to assist in AMR risk assessment.', 20, yPos);
    doc.text('It does not replace professional medical advice.', 20, yPos + 5);

    // Save
    doc.save(`Medication_Ninja_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};
